name: example                                                                                                                                
on: push                                                                                                                                                           
jobs:
        job_1:
                runs-on: ubuntu-latest
                steps:
                        - name: my first ci/cd
                          run: echo hello world
